# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-ideas-home-assignment-bl"
client_id = "879745352143885aa16127bf40a35e59"
application_url = "https://twice-live-eminem-graham.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://twice-live-eminem-graham.trycloudflare.com/auth/callback",
  "https://twice-live-eminem-graham.trycloudflare.com/auth/shopify/callback",
  "https://twice-live-eminem-graham.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-40.myshopify.com"
